// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpocsyehuojhwgknydgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwb2NzeWVodW9qaHdna255ZGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTMwNTEsImV4cCI6MjA2NDYyOTA1MX0.iJsyNu3eg2mQW3HrNRKGVPpL6Ce02DmdJWJu3vl_ztg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);